### ISSUE TITLE
client.in_battle() fails when the client flees

### ISSUE THREAD

**Issue by Slackaduts** [wizwalker/wizwalker#6]
Combat detection for a Client (client.in_battle()) returns True after the client flees.

**To Reproduce**
1.) Go into any battle and run await client.in_battle()
2.) Note that this returns the proper value, and flee.
3.) Run await client.in_battle() again. It will return True, even though you're no longer in combat.

**Expected behavior**
client.in_battle() should return False after fleeing, as we are no longer in combat.

**Comment by SirOlaf** [comment]
Should be fixed in 521c53a
